### ISSUE TITLE
Génération de PDF Personnalisables

### ISSUE THREAD

**Issue by babastienne** [Georiviere/Georiviere-admin#102]
**Besoin :**

Le candidat proposera une fonctionnalité visant à avoir une synthèse des principales informations des différents modules à l’échelle d’un cours d’eau. Les données à intégrer à cette synthèse seront les objets présents sur ou à proximité du cours d’eau de certains modules (à minima module connaissance, suivi, intervention, études). Le contenu de la synthèse (à définir avec le prestataire retenu) pourra se faire à partir d’une sélection des informations intégrées aux différents modules.

Cette synthèse devra être sous format pdf. Cette fonctionnalité a pour objectif de faire du reporting auprès des collectivités ayant transféré/délégué la compétence GEMAPI au Parc ainsi qu’aux financeurs et partenaires techniques. La mise en page de ce pdf devra donc être relativement graphique et pourra être paramétrer (logo, couleur…).

**Réponse :**

À la manière de Geotrek, il est souhaitable d’ajouter dans GeoRivière un moyen de générer des PDF à l’échelle d’un cours d’eau afin de pouvoir exporter les informations associées (objets liés).
Pour cette réalisation, nous prévoyons de réutiliser l’outil Weasyprint déjà éprouvé dans Geotrek. Cependant, des modifications seront effectués pour que le contenu du PDF puisse être personnalisable. Un certain degré de personnalisation sera autorisé (déterminé au démarrage de la prestation en accord avec le parc) et permettra de choisir les couleurs et la mise en forme du PDF, ainsi que les informations affichées (objets associés, champs des objets, photographies, logo, etc.).
Lors de la réalisation de cette prestation nous effectuerons un échange pour comprendre plus en détail le besoin du parc et nous appuyer sur des exemples de documents existants afin de pouvoir réaliser au mieux un modèle correspondant aux besoins réels.

**Comment by babastienne** [comment]
Pour les connaissances associées au cours d'eau il faut pouvoir afficher : le nom, le type, la position sur la carte
Suivi : type, nom, localisation, date
Intervention : nom, date, localisation, type
Etude : année, nom, type, localisation

**Comment by thomaspnrhj** [comment]
Desolé, pas encore eu le temps de m'y mettre, je fais ça au plus vite

**Comment by thomaspnrhj** [comment]
Voici un modèle @babastienne et @LePetitTim 

[Modele_reporting.pdf](https://github.com/Georiviere/Georiviere-admin/files/10999780/Modele_reporting.pdf)
