### ISSUE TITLE
Amélioration du module administratif

### ISSUE THREAD

**Issue by babastienne** [Georiviere/Georiviere-admin#106]
**Besoin :**

- La possibilité de pouvoir « phaser » un dossier administratif, ainsi un dossier administratif pourra être composé de plusieurs phases. Les phases sont repris dans un onglet Phases à l’instar de l’onglet Opération.
- C’est au niveau des phases que les budgets seront construits avec pour chaque phase, un budget prévisionnel, un budget ajusté et un budget réalisé. Ces budgets seront sommés au niveau du dossier administratif.
- Pour chaque phase, la possible de pouvoir lier une ou plusieurs opérations. Les coûts réalisés (coût matériel, coût sous-traitance et coût jour-homme) seront sommés pour le budget réalisé de la phase.
- D’ajouter un champ report au niveau des opérations en cas de reports d’actions avec les valeurs suivantes : report géographique (modification de la localisation de l’opération sur une même masse d’eau), report d’une masse d’eau à une autre (opération prévue sur un cours d’eau et réalisée sur un autre cours d’eau par
- exemple) et report temporel (d’une année à l’autre)
- De pouvoir ajouter un objet en tant qu’opération à une phase depuis sa fiche (actuellement uniquement possible depuis le module dossier administratif).

**Réponse :**

Dans le cadre des développements, le module administratif déjà existant dans l’application sera amélioré afin de couvrir un besoin métier plus complexe qu’actuellement. Ainsi, il conviendra de re-prendre et d’adapter le fonctionnement des Opérations afin de l’adapter un système de workflow disponible via un onglet « Phases ». Chaque phase pourra avoir une ou plusieurs opérations propre.
Le module devra laisser la possibilité de renseigner plusieurs budgets par phase, indépendamment du lien avec les opérations, mais également d’utiliser les opérations associées auphase pour pré-calculer le budget estimé. Les budgets totaux seront additionnés dans la vue générale du dossier administratif.

Question à traiter en amont des développements : Une opération pourra-t-elle être créée sans être associée à une phase ? -> Non

Pour rappel, les opérations sont actuellement associées à plusieurs types d’objets. Pour le moment le lien est possible dans un sens uniquement, avec dans le module administratif la sélection au moment de la saisie d’une opération de l’objet associé. Il faudra mettre en place le mécanisme inverser, permettant depuis la fiche détail d’un objet de sélectionner un dossier administratif associé ainsi que sa phase afin d’y ajouter une opération.
Enfin, les opérations seront modifiées afin d’y ajouter une notion de report permettant d’expliciter la cause de report de réalisation d’une opération.

**Comment by LePetitTim** [comment]
* La possibilité de pouvoir « phaser » un dossier administratif, ainsi un dossier administratif pourra être composé de plusieurs phases. Les phases sont repris dans un onglet Phases à l’instar de l’onglet Opération.

Une opération n'appartien qu'a une seule phase


* D’ajouter un champ report au niveau des opérations en cas de reports d’actions avec les valeurs suivantes : report géographique (modification de la localisation de l’opération sur une même masse d’eau), report d’une masse d’eau à une autre (opération prévue sur un cours d’eau et réalisée sur un autre cours d’eau par exemple) et report temporel (d'une année à l'autre)

Le champ report sera configurable. Chaque opération poura avoir plusieurs report possible et pourra être sans report.

**Comment by thomaspnrhj** [comment]
Tout est ok pour moi, le rendu dans la fiche est top. Par contre, quand on créé un dossier administratif, valeur obligatoire "opérations sur" dans opérations qui bloque la création, alors qu'il faut enregistrer pour avoir les phases et on connait pas forcément les opérations à la création, ne pas rendre obligatoire
