### ISSUE TITLE
Association de fichier lié (chemin vers le fichier)

### ISSUE THREAD

**Issue by babastienne** [Georiviere/Georiviere-admin#112]
Le besoin consiste à ajouter une quatrième catégorie de fichier lié qui serait un "chemin vers fichier" pour permettre d'avoir un lien qui ouvre un explorateur de fichier sur le serveur associé.

**Comment by thomaspnrhj** [comment]
Le lien doit être de type href="file:///
Exemple : 
![image](https://user-images.githubusercontent.com/19687397/222174278-0d85bea1-f32f-4f45-86d8-9bf64f240c5b.png)

**Comment by camillemonchicourt** [comment]
Je trouve ça un peu étonnant et discutable pour une application web de stocker des liens vers un fichier sur un serveur local... Donc pas accessibles si on n'est pas dans ce réseau, et dont le chemin peut changer facilement...

Soit on fait un lien relatif vers un fichier stocké localement sur le serveur de l'application, soit un lien absolu vers l'URL d'un fichier distant en HTTP.

Après je comprends le besoin de ne pas dupliquer des fichiers déjà présents sur un serveur local.

**Comment by thomaspnrhj** [comment]
@camillemonchicourt oui on a bien conscience que ces documents ne seront pas accessibles hors réseau... Pour les documents que l'on veut partager, bien évidemment on les stockera sur le serveur web pour l'accès. L'idée est de ne pas dupliquer des documents uniquement interne (doc administratif, financier...). Et c'est une demande assez forte d'autres utilisateurs potentiels.
On va plutôt aller sur la possibilité de pouvoir générer un lien hypertexte dans un bloc html dans le champ de description (bloc texte pour l'instant), Makina regarde ça. Ca évite de la confusion sur les fichiers partagés.
