### ISSUE TITLE
Ajout classement dans module cours d'eau

### ISSUE THREAD

**Issue by thomaspnrhj** [Georiviere/Georiviere-admin#117]
Ajouter l'attribut "Classement police de l'eau" dans le module cours d'eau sous forme de liste déroulante : classé cours d’eau, non cours d’eau, reclassement demandé, reclassement à faire, à déterminer

**Comment by babastienne** [comment]
Champ : liste déroulante qui permet de sélectionner une seule valeur. Valeurs modifiable dans l'admin
Valeurs par défaut : classé cours d’eau, non cours d’eau, reclassement demandé, reclassement à faire, à déterminer
Ajouter le champ en dernier dans vue détail. En profiter pour enlever le champ "emplacement de la source"

**Comment by thomaspnrhj** [comment]
Ajout du champ dans les filtres !

**Comment by thomaspnrhj** [comment]
Ok pour moi
