### ISSUE TITLE
GRA Pouvoir afficher les cours d'eau du territoire

### ISSUE THREAD

**Issue by babastienne** [Georiviere/Georiviere-admin#132]
Besoin expirmé : 

> Les cours d’eau du territoire : il s’agira d’afficher directement les cours d’eau présent dans une instance GeoRivière admin, depuis le module cours d’eau. Au clic du cours d’eau, un pop-up s’affichera avec le nom du cours d’eau, ses caractéristiques (longueur, dénivelé…), une description du cours d’eau et d’un ou plusieurs médias (photos, sons ou vidéos) ;

Côté GRA : 

- [x] Mettre en place une notion de publication sur les cours d'eau existants (booléen)
- [x] Ajouter un champ "Description" qui sera destiné à la valorisation
- [ ] Renvoyer sur l'API les champs suivants : description, nom, taille, dénivelé, écoulement

**Comment by LePetitTim** [comment]
fonctionnement directement avec des portails et non pas avec "publiés".

Lorsqu'on ajoute un portail, il ets forcement publié pour ce portail.

**Comment by Govthub** [comment]
> fonctionnement directement avec des portails et non pas avec "publiés".
> 
> Lorsqu'on ajoute un portail, il est forcement publié pour ce portail.

What is your issues . I can fixed it
