### ISSUE TITLE
Détailler les types de contribution et les éléments attendus de la part des contributeurs

### ISSUE THREAD

**Issue by babastienne** [Georiviere/Georiviere-admin#139]
D'après le cahier des charges : 

> Les contributions porteront sur les enjeux :
> - Qualité : les contributeurs pourront signaler diverses perturbations pouvant traduire un dysfonctionnement comme des hydrocarbures, des mousses, des effluents d’élevage, des déchets, etc ;
> - Faune/Flore : à la manière de certaines bases de données naturalistes, les contributeurs pourront faire remonter leurs observations d’espèces remarquables/protégées/invasives, pour lesquelles des enjeux d’action peuvent exister ;
> - Quantité : disposer d’images de références concernant les évènements majeurs en termes d’étiages et de crues requiert pour les gestionnaires un temps important. La présence sur le terrain de riverains pouvant transmettre des images sera un réel plus pour la connaissance du territoire ;
> - Dégâts potentiels : les contributeurs pourront faire remonter la présence d’embâcles risquant de poser des désagréments à des infrastructures ou d’érosion de berges potentiellement dangereuses.

Pour chacune des catégories, est-il possible d'avoir le détail des champs attendus que les utilisateurs devront remplir dans le formulaire ?

J'identifie déjà : 
- Nom / Prénom / Mail
- Date de l'observation / contribution
- Description

Faut-il limiter la description à un certains nombre de caractères ?
Il faut indiquer le niveau de gravité ? (demandé lors des ateliers citoyens) Si oui quelle échelle utiliser ?
Il faut l'heure de l'observation ? 
Quels sont les types de contribution pour chaque catégorie ? 
Une photo est-elle obligatoire ? Si oui pour toutes les contributions ou seulement pour certains types ?

Ca serait bien d'avoir un tableau récapitulatif pour chaque type de contribution des champs attendus, quelque chose du style : 

### Récap (EXEMPLE)

**Champs communs à l'ensemble des contributions**

| Nom du champ | Type | Info complémentaire |
|---------------------|----------------------------|-------------------------|
| Nom du contributeur | Text | Max 50 caractères |
| Prénom du contributeur | Text | Max 50 caractères |
| Email du contributeur | Email | Max 200 caractères. Champ facultatif |
| Catégorie de la contribution | Liste déroulante | Choix parmi : Dégats potentiels / Quantité / Faune-Flore / Qualité |
| Date de l'observation | Date | Ne doit pas prendre en compte l'heure. Par défaut date du jour. Champ obligatoire |

**Champs spécifiques pour les contribution "Qualité"**

| Nom du champ | Type | Info complémentaire |
|---------------------|----------------------------|-------------------------|
| Photographie |Image | 3 images obligatoires |
| Etc. |  |  |

**Champs spécifiques pour les contribution "Faune-Flore"**

| Nom du champ | Type | Info complémentaire |
|---------------------|----------------------------|-------------------------|
| ... |  |  |

**Champs spécifiques pour les contribution "Dégâts potentiels"**

| Nom du champ | Type | Info complémentaire |
|---------------------|----------------------------|-------------------------|
| ... |  |  |

**Champs spécifiques pour les contribution "Quantité"**

| Nom du champ | Type | Info complémentaire |
|---------------------|----------------------------|-------------------------|
| ... |  |  |

**Comment by babastienne** [comment]
Si il y a un ordre de champs à remplir dans l'interface il faudrait également nous le préciser.

**Comment by thomaspnrhj** [comment]
**Champs communs :** 

<html><body>


Nom du champ | Type | Info complémentaire
-- | -- | --
Nom du contributeur | Texte | Max 50 caractères. Champ facultatif
Prénom du contributeur | Texte | Max 50 caractères. Champ facultatif
Email du contributeur | Email | Max 200 caractères. Champ obligatoire
Catégorie de la contribution | Liste déroulante | Choix parmi : Dégâts potentiels / Quantité / Faune-Flore / Qualité / Éléments paysagers. Champ obligatoire
Date de l'observation | Date | Doit prendre en compte l'heure. Par défaut date du jour. Champ obligatoire
Gravité |  Liste déroulante  | Choix parmi : Faible, Modéré, Fort. Champ facultati
Description | Texte | Max 500 caractères. Champ facultatif
Photographie | Image | jusqu'à trois images, facultatif

</body>
</html>

**Catégorie Dégâts potentiels** 

<html><body>


Nom du champ | Type | Info complémentaire
-- | -- | --
Type | Liste déroulante | Choix parmi : Atterrissement / Coupe abusive de ripisylve /  Eboulements / Embâcle perturbateur / Erosion de la berge / Incision du lit (enfoncement) / Maladies piscicoles (aspect des poissons) / Mortalité piscicole / Piétinement par le bétail (impactant) . Champ obligatoire
Si atterrissement : type atterrissement | Liste déroulante | Partiel en berge, Partiel au milieu du lit, Total
Si Coupe abusive de ripisylve : linéaire | Nombre | en mètres
Si embâcle perturbateur : type embâcle | Liste déroulante | Partiel en berge, Partiel ai milieu du lit, Total
Si érosion de la berge : Distance entre le pied de berge et le pied de l'érosion | Nombre | en mètres
Si  Incision du lit (enfoncement) : Hauteur de berge (mesurée entre le pied de berge et le haut de berge) | Nombre | en mètres
Si Maladies piscicoles (aspect des poissons) : Type maladie | Liste déroulante | Excroissances blanchâtres, Léthargie, Points blancs, Ulcérations
Si Mortalité piscicole : Nombre individus | Nombre| 
Si Mortalité piscicole : Espèces | Liste déroulante | Barbeau, Blageon, Brochet, Chabot, Chevesne, Goujon, Lamproie, Loche franche, Lotte, Ombre commun, Spirlin, Toxostome, Truite fario, Vairon, Vandoise

</body>
</html>


**Catégorie Faune-Flore** 

<html><body>


Nom du champ | Type | Info complémentaire
-- | -- | --
Type | Liste déroulante | Choix parmi : Espèce invasive / Espèce patrimoniale / Espèce piscicole
Si Espèce invasive : Surface du foyer | Nombre | en mètres
Si Espèce invasive : Espèces | Liste déroulante | Ecrevisse américaine, Ambroisie à feuille d'armoise, Balsamine de l'Himalaya, Berce du caucase, Buddleia (ou arbre à papillons), Elodée du canada, Renouées asiatiques, Solidage (ou verge d'or)
Si Espèce patrimoniale : Nombre d'individus  | Nombre | 
Si Espèce patrimoniale : Espèces | Liste déroulante | Écrevisse à pattes blanches, Salamandre tachetée, Sonneur à ventre jaune
Si Espèce piscicole : Nombre d'individus  | Nombre | 
Si Espèce piscicole : Espèces | Liste déroulante | Barbeau, Blageon, Brochet, Chabot, Chevesne, Goujon, Lamproie, Loche franche, Lotte, Ombre commun, Spirlin, Toxostome, Truite fario, Vairon, Vandoise

</body>
</html>

**Catégorie Quantité ** 

<html><body>


Nom du champ | Type | Info complémentaire
-- | -- | --
Type niveau d'eau | Liste déroulante | A sec, En cours d'assèchement, Débordement
Si Débordement : Repère | Texte | Max 500 caractères. 


</body>
</html>


**Catégorie Qualité ** 

<html><body>


Nom du champ | Type | Info complémentaire
-- | -- | --
Type qualité eau | Liste déroulante |  Développement algal, Pollution, Température de l'eau
Si Pollution : Nature pollution | Liste déroulante | Déchets, Effluents d'élevage, Hydrocarbures, Présence abondante de mousse
Si Pollution : Type pollution  | Liste déroulante | visible, olfactive


</body>
</html>

**Catégorie Éléments paysagers** 

<html><body>


Nom du champ | Type | Info complémentaire
-- | -- | --
Type  | Liste déroulante | Doline, Fontaine, Gouffre, Lésine, Mare, Perte, Résurgence

</body>
</html>
