### ISSUE TITLE
Fichiers attachés

### ISSUE THREAD

**Issue by babastienne** [Georiviere/Georiviere-admin#146]
Sur les fichiers attachés : 

- [ ] Ajouter une notion de favoris (étoile comme dans Geotrek)
- [ ] Ajouter un booléen "public". si non coché alors le fichier ne sera pas remonté dans l'API (permet au parc de conserver des fichiers à usage interne)

**Comment by LePetitTim** [comment]
Ne faut il pas plutot mettre le meme fonctionnement que dans le reste de l'applicaiton avec portals
