### ISSUE TITLE
Absence d'attribution OpenStreetMap

### ISSUE THREAD

**Issue by flacombe** [Georiviere/Georiviere-admin#186]
Bonjour

En consultant la version de démo déployée par OpenIG, je constate l'absence d'attribution du fond de carte OpenStreetMap utilisé.
Cette absence se retrouve ensuite dans tous les visuels qui montrent l'interface.
Il me semble que c'est une absence généralisée à l'ensemble du projet sans être propre à la démo.

Pouvez-vous faire le nécessaire pour respecter https://osm.org/copyright s'il vous plaît ?

Je suis surpris d'avoir à l'indiquer ici, connaissant la structure du projet et ses partenaires.
OpenStreetMap France est intéressée pour connaître les raisons qui ont entraîné cet oubli pour améliorer son accompagnement et l'éviter par la suite.

Bonne journée

**Comment by camillemonchicourt** [comment]
Merci pour cette vigilance et alerte.

Dans la configuration par défaut intégrée au projet, il semble en effet que l'outil soit proposé avec le fond de base OSM, pour lequel l'attribution est bien définie : https://github.com/Georiviere/Georiviere-admin/blob/master/georiviere/settings/__init__.py#L349-L354

2 possibilités : 
- Soit l'attribution est bien définie mais il y a un oubli et l'outil ne l'affiche pas, ou un bug est apparu et elle ne s'affiche plus sur les cartes
- Soit l'attribution fonctionne bien, mais la configuration du fond de carte a été surcouchée et modifiée sur l'instance de démo d'OpenIG et c'est lié à leur configuration

Je penche plutôt pour la première piste, car je vois que dans Geotrek-admin aussi (qui partage le même cœur technique que Georiviere-admin), les attributions ne s'affichent plus sur les différentes cartes.

Donc il semble que cela soit une régression récente de Django-mapentity, cœur commun de Geotrek-admin et Georiviere-admin.

**Comment by flacombe** [comment]
Merci pour le retour rapide et les explications.

Est-ce qu'il est nécessaire d'ouvrir un ticket ailleurs ou c'est propre à l'usage de Django-mapentity dans les socles communs ?

**Comment by camillemonchicourt** [comment]
Il est pertinent de remonter le soucis dans le dépôt de Django-mapentity si il est confirmé que le soucis est à ce niveau et qu'il y a bien eu une régression sur Django-mapentity qui affecte Geotrek-admin et Georiviere-admin, mais là je laisse les développeurs confirmer ou non.

**Comment by babastienne** [comment]
Résolu pour GeoRiviere via : https://github.com/makinacorpus/django-mapentity/pull/271.

Inclut dans la dernière release

**Comment by flacombe** [comment]
C'est parfait, je vous remercie.
Je verrai la correction dans la prochaine release.

Bonne semaine.

**Comment by camillemonchicourt** [comment]
La répercussion est déjà effective et publiée sur Geotrek-admin : 

![image](https://github.com/Georiviere/Georiviere-admin/assets/4418840/3ab7f5c1-6e04-4745-a2b3-189dd7101722)
