### ISSUE TITLE
GRA : Gestion des contributions

### ISSUE THREAD

**Issue by LePetitTim** [Georiviere/Georiviere-admin#199]
- [x] Envoyer une notification au gestionnaire comme dans Geotrek, notification par mail
- [x] Envoyer un mail de prise en compte au signaleur comme dans Geotrek lorsque la contribution arrive dans GeoRiviere
- [x] Comme dans Signalements, il faut ajouter un champ statut (informé, en cours de traitement, traité, retour au contributeur) et un champ gestionnaire (liste des utilisateurs de GeoRiviere). Ces champs seront privés et non publiés dans l'API. Il doit être possible de filtrer la vue liste via ces champs.
- [x] Ajout d’un champ validé sous forme de case à cocher (booléen). Champ interne. Possibilité de filtrer sur ce champ la liste.
- [x] Dans la vue liste, retirer les colonnes "portail", "Nom de l’auteur" et "mail".
- [x] Dans la vue liste ne plus avoir de champ "nom" mais deux champs Catégorie / Type. Pouvoir filtrer par catégorie et par type la liste.
- [x] Pouvoir gérer des genericForeignKey afin de lier une contribution à des objets : connaissance / suivi / intervention

**Comment by LePetitTim** [comment]
Sur le dernier point, il faut que ce soit possible de lier une contribution a plusieurs objets ?

**Comment by LePetitTim** [comment]
Il ne reste plus qu'a faire une release

**Comment by babastienne** [comment]
Pour recevoir les mails il faut activer la configuration correspondante : https://georiviere.readthedocs.io/en/stable/usage/configuration.html#email-settings

**Comment by babastienne** [comment]
Au même titre que Geotrek, le contenu des mails peut être surchargé via les traductions

**Comment by babastienne** [comment]
- [ ] Dans les modules Connaissance, Intervention, etc., il faut pouvoir depuis la fiche détail d'un itinéraire accéder à la contribution associée

**Comment by thomaspnrhj** [comment]
Dans la dernière version : 
J'ai un message d'erreur quand je transmets une contribution : 
![Image](https://github.com/Georiviere/Georiviere-admin/assets/19687397/3ced7a89-e4de-4463-98cd-18894be9e8e6)

Et aucune contribution ne remonte dans G.Admin

**Comment by babastienne** [comment]
Je confirme reproduire le problème.

**Comment by thomaspnrhj** [comment]
Les contributions fonctionnent à nouveau avec la nouvelle release 0.1.3 
Juste encore une erreur sur Dégâts potentiels>Embâcle car une valeur n'existe pas JamType, champ à supprimer
![image](https://github.com/Georiviere/Georiviere-admin/assets/19687397/07640081-4c04-41fa-b5c9-dfa7e77e2115)
