### ISSUE TITLE
Fournir une fiche de saisie et la logique associée

### ISSUE THREAD

**Issue by babastienne** [Georiviere/Georiviere-admin#233]
Distinguer les éléments suivants : 
- Protocole : les informations relevées par les élèves
- Formulaire : ce qui sera demandé de saisir en ligne sur GeoRivière
- Table de stockage : la manière dont sont stockée les données en base

Merci de nous donner le plus d'informations possibles pour qu'on puisse adapter les formulaires en fonction des contenus communiqués.

**Comment by babastienne** [comment]
> A articuler/harmoniser avec les standards de Méta-données du SINP ou autre standard de Méta-données plus global ?

L'idée là est d'avoir une fiche protocole associée au besoin de l'AEAG. Cela sera configuré dans un JSONSchema générique qui permet à chaque territoire de créer le formulaire qu'il souhaite contrairement à ce qui est réalisé actuellement. 

Ce ticket est là pour permettre d'obtenir les données, si tu veux plus d'infos sur ce qui va être développé @camillemonchicourt je t'invites à aller voir plutôt [ce ticket](https://github.com/orgs/Georiviere/projects/3/views/1?pane=issue&itemId=57761577).

**Comment by bernardhypolite** [comment]
Bonjour,

Les fiches ne sont pas complètement stabilisées, j'essaierai de vous les faire passer semaine prochaine.

Voici un doc qui donne un idée assez précise des éléments qui seront à saisir.

En jaune les indicateurs à saisir, en vert les valeurs possibles.


L'idée pour nous serait de pouvoir stocker les paramètres dans une table de type : 
code station | identifiant de l'opération de prélèvement | date heure | code du paramètre | libellé paramètre | valeur | unité | 

A votre disposition si ce n'est pas très clair




[ProtocoleSaisie.docx](https://github.com/Georiviere/Georiviere-admin/files/14979294/ProtocoleSaisie.docx)

**Comment by bernardhypolite** [comment]
Correction suite à réunion de mardi dernier et la réponse sur les futurs protocoles.

Il est à notre avis plus simple de parler de fiche de saisie plutôt que de protocole.
Exemple, fiche de saisie Lycée et fiche de saisie Collège.
La liste des protocoles pour une fiche n'a pas d'importance.

Pour le démonstrateur, de toute façon, on ne prévoir qu'une fiche.


Voici en PJ un exemple pour la partie description de la station mais c'est encore en test.

[Diagnostic-riviere-A4.pdf](https://github.com/Georiviere/Georiviere-admin/files/15041828/Diagnostic-riviere-A4.pdf)
