### ISSUE TITLE
Données à intégrer / contenus pour Georiviere

### ISSUE THREAD

**Issue by babastienne** [Georiviere/Georiviere-admin#241]
Données à nous envoyer pour intégration et configuration de l'instance GeoRivière-Admin : 
- [x] Stations sur lesquelles les protocoles seront réalisés / rattachés
- [x] Masses d'eau DCE
- [x] Cours d'eau à intégrer
- [x] Périmètre du territoire couvert
- [ ] Zones sensibles
- [ ] Contenus des pages statiques / visuels et fichiers attachés
- [ ] Liste des utilisateurs à créer dans l'application (à communiquer plutôt par mail ?)

Pour le site public, il faudra aussi nous communiquer : 
- [ ] Les logos / illustrations / images à mettre sur le site
- [ ] Quelques informations sur la mise en page souhaitée pour la page d'accueil
- [ ] Charte graphique à respecter (couleur, police, etc.)
- [ ] Contenu des mentions légales

**Comment by bernardhypolite** [comment]
Voici le premières données en intégrer :

Périmètre du territoire : BassinAdourGaronne
Stations
Cours

[CouchesGeo.zip](https://github.com/Georiviere/Georiviere-admin/files/14955100/CouchesGeo.zip)

 d'eau
Bassin versants de masses d'eau

**Comment by babastienne** [comment]
Merci @bernardhypolite 

Je viens d'intégrer certaines des données transmises. Par contre je n'ai trouvé aucune données dans les couches "CoursEau" et "Stations", je pense qu'il faut nous redonner des fichiers avec les données, il y a du avoir une erreur dans la sauvegarde.

**Comment by bernardhypolite** [comment]
Voici un nouvel export. En effet, la taille des fichiers était très petite.

[CouchesGeo.zip](https://github.com/Georiviere/Georiviere-admin/files/14975386/CouchesGeo.zip)

**Comment by xcaeag** [comment]
manque-t-il quelque chose ?

**Comment by babastienne** [comment]
Envoyer une règle pour filtrer les cours d'eau à intégrer en priorité afin de réduire la volumétrie des données.

**Comment by bernardhypolite** [comment]
Voici un nouvel export de cours d'eau ( environ  3500 au lieu de 38000 ) en geopackage

[CoursEau.zip](https://github.com/Georiviere/Georiviere-admin/files/15007494/CoursEau.zip)

**Comment by babastienne** [comment]
Merci @bernardhypolite pour ces nouveaux éléments

_________

Pour tracer dans le suivi, le script utilisé pour importer les Stations : 

<details><summary>Code source</summary>
<p>

```python
from django.contrib.gis.gdal import DataSource
from georiviere.observations.models import Station, StationProfile  
from geotrek.authent.models import Structure

sp, _ = StationProfile.objects.update_or_create(code="STQ", label="Station qualité")
structure = Structure.objects.first()

ds = DataSource('/opt/georiviere-admin/var/conf/Stations.shp')

for feat in ds[0]:
    try:
        geom = feat.geom.geos
        geom.dim = 2
        desc = f"Adresse : {feat.get('complement')}\n{feat.get('nom_commun')}\n\nDate de mise en service : {feat.get('date_servi')}\n\nFinalite : {feat.get('finalite_a')}"
        station_obj, station_created = Station.objects.update_or_create(
            code=feat.get('numero'),
            label=feat.get('libelle'),
            defaults={
                'purpose_code': feat.get("finalite") or "",
                'description': desc,
                'in_service': True,
                'geom': geom,
            }
        )
        station_obj.station_profiles.add(sp)
        station_obj.save()
    except Exception as exc:
        print(e)
```

</p>
</details>

**Comment by bernardhypolite** [comment]
Voici un zip avec les éléments de charte graphiqueet les logos


[Charte.zip](https://github.com/Georiviere/Georiviere-admin/files/15041851/Charte.zip)

 J'ai aussi ajouté un ppt d'exemple de page pour le site


[MaquetteSite.pptx](https://github.com/Georiviere/Georiviere-admin/files/15041898/MaquetteSite.pptx)

J'ai également une vidéo mais je ne sais pas si je peux la poser ici
