### ISSUE TITLE
import data dem

### ISSUE THREAD

**Issue by pnrm** [Georiviere/Georiviere-admin#76]
Bonjour,
Installation avec docker sous ubuntu 20 server
Lors de l'importation de l'altimétrie dans GéoRivière avec 
`docker-compose run --rm web ./manage.py loaddem /opt/georiviere-admin/var/dem.tiff`
Starting georiviere_convertit_1     ... done
Starting georiviere_postgres_1      ... done
Starting georiviere_memcached_1     ... done
Starting georiviere_screamshotter_1 ... done
Waiting for postgres...
PostgreSQL started
/bin/sh: 1: raster2pgsql: not found
CommandError: Caught Exception: raster2pgsql failed with exit code 127

Visiblement il manque l'extension raster2pgsql
Comment rajouter cette dernière ?
Merci

**Comment by submarcos** [comment]
Bonjour,
il manque une librairie dans le Dockerfile.

Une modification est en cours, çà devrait être fixé dans la prochaine version.

**Comment by pnrm** [comment]
Merci
