### ISSUE TITLE
Affichage cities/distrcits

### ISSUE THREAD

**Issue by thomaspnrhj** [Georiviere/Georiviere-admin#78]
J'ai chargé mes cities et districts, ils sont bien dans la BD, visible depuis monQGIS, et repertorier dans les fiches des objets. Par contre il n' s'affiche pas sur la carte. J'ai vidé mon cache et lancé un docker compose restart mais toujours rien. Une commande particulière à lancer ?

**Comment by numahell** [comment]
Hello, normalement non, pas de commande supplémentaire.

Est-ce que ce sont les raccourcis en haut de la carte pour aller sur la zone qui ne s'affichent pas, ou bien les couches de la carte ?

**Comment by thomaspnrhj** [comment]
Les entités sur la carte uniquement : 
![image](https://user-images.githubusercontent.com/19687397/171596945-0b771292-19e9-4675-8fb3-3ae627018253.png)

**Comment by thomaspnrhj** [comment]
@numahell je ne sais pas comment ni purquoi mais depuis ce matin l'affichage est ok, peut-être le fait d'avoir relancer docker compose down et docker compose up ???
