### ISSUE TITLE
Ajout des BV

### ISSUE THREAD

**Issue by thomaspnrhj** [Georiviere/Georiviere-admin#79]
Dans la doc, je ne trouve pas la façon de procédé à l'import des BV, j'ai tester docker compose run --rm web ./manage.py loadwatershed data sur la meme base que cities et districts mais inconnu

**Comment by numahell** [comment]
Il n'y a pas aujourd'hui de commande dédiée à l'import des bassins versants. Ça passe pour le moment par un script utilisant Gdal, sur le même modèle que l'import du référentiel.

**Comment by thomaspnrhj** [comment]
Ok je regarde pour adapter le modèle alors ! à voir pour simplifier ça dans la V2

**Comment by thomaspnrhj** [comment]
Super merci, il manque à priori le code pour django.contrib.gis.geos.collections
J'ai ajouté from django.contrib.gis.geos.collections import MultiPolygon
![image](https://user-images.githubusercontent.com/19687397/171634354-07821da7-6577-4d0c-960f-c575d557ebfd.png)

Par contre c'est bizarre si le nom du fichier n'est pas import_bdtopage.py, il n'arrive pas à la lancer :
![image](https://user-images.githubusercontent.com/19687397/171633684-159e7c5c-c194-42f4-9991-8fed81bebeb3.png)

**Comment by thomaspnrhj** [comment]
Bon j'ai fait et refait, je tombe systématiquement sur cette erreur :   

File "/opt/venv/lib/python3.9/site-packages/django/contrib/gis/db/models/proxy.py", line 74, in __set__
    raise TypeError('Cannot set %s SpatialProxy (%s) with value of type: %s' % (
TypeError: Cannot set Watershed SpatialProxy (MULTIPOLYGON) with value of type: <class 'django.contrib.gis.geos.polygon.Polygon'>

Est-ce une arreur dans le code ? ou une mise à jour d'une libraire python à faire ?

**Comment by thomaspnrhj** [comment]
En intégrant les BV dans watershed_watershed, ils remontent bien dans la carte + filtre + objets intersectés, on va garder cette option plus simple ;-)
